using UnityEngine;

namespace NAK.Stickers;

internal enum KeyBind
{
    A = KeyCode.A,
    B = KeyCode.B,
    C = KeyCode.C,
    D = KeyCode.D,
    E = KeyCode.E,
    F = KeyCode.F,
    G = KeyCode.G,
    H = KeyCode.H,
    I = KeyCode.I,
    J = KeyCode.J,
    K = KeyCode.K,
    L = KeyCode.L,
    M = KeyCode.M,
    N = KeyCode.N,
    O = KeyCode.O,
    P = KeyCode.P,
    Q = KeyCode.Q,
    R = KeyCode.R,
    S = KeyCode.S,
    T = KeyCode.T,
    U = KeyCode.U,
    V = KeyCode.V,
    W = KeyCode.W,
    X = KeyCode.X,
    Y = KeyCode.Y,
    Z = KeyCode.Z,
    Mouse0 = KeyCode.Mouse0,
    Mouse1 = KeyCode.Mouse1,
    Mouse2 = KeyCode.Mouse2,
    Mouse3 = KeyCode.Mouse3,
    Mouse4 = KeyCode.Mouse4,
    Mouse5 = KeyCode.Mouse5,
    Mouse6 = KeyCode.Mouse6,
}