name: Update Mod List

on:
  push:
    paths:
      - '.github/scripts/update-modlist.js'
      - '.github/workflows/update-modlist.yml'
      - 'README.md'
      - '**/README.md'
  workflow_dispatch:

jobs:
  update-modlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run mod list updater
        run: node .github/scripts/update-modlist.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "[NAK_CVR_Mods] Update mod list in README" || echo "No changes to commit"
          git push